var places_list = 
[
  {
    'title' : 'Front Gate',
    'description1' : 'This is the Front Gate',
    'description2' : 'Your next stop is the Admission Office',
    'lat' :  34.0587707, 
    'lng' : -117.8190623,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Admission Office',
    'description1' : 'This is the Admission Office',
    'description2' : 'Your next stop is the Alf Museum',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Alf Museum',
    'description1' : 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
    'description2' : 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
    'lat' : 34.123754,
    'lng' : -117.739179,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Science Building',
    'description1' : 'This is the Science Building',
    'description2' : 'Your next stop is the Fawcett Library',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Fawcett Library',
    'description1' : 'This is the Fawcett Library',
    'description2' : 'Your next stop is the Old School House',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Liu Cheung Theather',
    'description1' : 'This is the Liu Cheung Theater',
    'description2' : 'Your next stop is the Hooper Student Center',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Hooper Student Center',
    'description1' : 'This is the Hooper Student Center',
    'description2' : 'Your next stop is the Price Dining Hall',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Price Dining Hall',
    'description1' : 'This is the Price Dining Hall',
    'description2' : 'Your next stop is the Copeland Donahue Theater',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Copeland Donahue Theater',
    'description1' : 'This is the Copeland Donahue Theater',
    'description2' : 'Your next stop is the Vivian Webb Chapel',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Vivian Webb Chapel',
    'description1' : 'This is the Vivian Webb Chapel',
    'description2' : 'Your next stop is the Aquatics Center',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Aquatics Center',
    'description1' : 'This is the Aquatics Center',
    'description2' : 'Your next stop is the Dorm (WSC)',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Dorm (WSC)',
    'description1' : 'This is the Dorm (WSC)',
    'description2' : 'Your next stop is the Dorm (VWS)',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
  {
    'title' : 'Dorm (VWS)',
    'description1' : 'This is the Dorm (VWS)',
    'description2' : 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
    'lat' : 42.345573, 
    'lng' : -71.098326,
    'heading' : 34,
    'pitch' : 10,
  },
];
