var places_list =
  [
    {
      'title': 'Front Gate',
      'description1': 'This is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front Gate',
      'description2': 'Your next stop is the Admission OfficeThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front GateThis is the Front Gate',
      'lat': 34.121775,
      'lng': -117.738745,
      'heading': 50,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Inside gate',
      'description1' : 'This is the Admission Office',
      'description2': 'Your next stop is the Alf Museum',
      'lat': 34.1229888,
      'lng': -117.7390033,
      'heading': 10,
      'pitch': 10,
    },
    {
      'title': 'Admission Office',
      'description1': 'This is the Admission Office',
      'description2': 'Your next stop is the Alf Museum',
      'lat': 34.1233833,
      'lng': -117.7383917,
      'heading': 190,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Alf Museum',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1235167,
      'lng': -117.7387117,
      'heading': 165,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Alf Museum2',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1234612,
      'lng': -117.7388167,
      'heading': 150,
      'pitch': 10,
    },
    {
      'title': 'Alf Museum3',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.123525,
      'lng': -117.7387367,
      'heading': 34,
      'pitch': 10,
    },
    {
      'title': 'Alf Museum4',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1235222,
      'lng': -117.73893,
      'heading': 215,
      'pitch': 10,
    },
    {
      'title': 'Alf Museum5',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1235,
      'lng': -117.73877,
      'heading': 175,
      'pitch': 10,
    },
    {
      'title': 'Paleontology Lab',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1233055,
      'lng': -117.7388717,
      'heading': 325,
      'pitch': 0,
    },
    {
      'title': 'Paleontology Lab2',
      'description1': 'Welcome to the Raymond Alf Museum! Webb is the only high school in the world with an accredited paleontology museum on its campus! The Alf Museum is home to 175,000 specimens, 95% of which were found by Webb community members. Webb students have the opportunity to work at the museum and can take classes in paleontology and museum studies.',
      'description2': 'All Webb students are invited to participate in paleontology digs, or "peccary trips." 9th grade students travel to Barstow, CA to look for fossils as part of Webb’s freshman orientation program. Summer peccary trips have also taken students to Montana, Utah, Madagascar, Mongolia and Peru!',
      'lat': 34.1227,
      'lng': -117.73892,
      'heading': 180,
      'pitch': 0,
    },
    {
      'title': 'Science Building',
      'description1': 'This is the Science Building',
      'description2': 'Your next stop is the Fawcett Library',
      'lat': 34.1234833,
      'lng': -117.7390583,
      'heading': 0,
      'pitch': -10,
      'marker' : 'True',
    },
    {
      'title': 'Fawcett Library',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1238972,
      'lng': -117.739125,
      'heading': -5,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Fawcett Library2',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1239805,
      'lng': -117.7389133,
      'heading': 0,
      'pitch': 0,
    },
    {
      'title': 'Fawcett Library Classroom',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.124125,
      'lng': -117.738925,
      'heading': 150,
      'pitch': 10,
    },
    {
      'title': 'Jackson Library',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1237583,
      'lng': -117.7384417,
      'heading': 195,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Jackson Library2',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1236278,
      'lng': -117.7381867,
      'heading': -5,
      'pitch': 5,
    },
    {
      'title': 'Old School House',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1241112,
      'lng': -117.7393583,
      'heading': 0,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Old School House2',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1240667,
      'lng': -117.7392167,
      'heading': 220,
      'pitch': 10,
    },
    {
      'title': 'Old School House Classroom',
      'description1': 'This is the Fawcett Library',
      'description2': 'Your next stop is the Old School House',
      'lat': 34.1240667,
      'lng': -117.739745,
      'heading': -25,
      'pitch': 10,
    },
    {
      'title': 'Liu Cheung Theather',
      'description1': 'This is the Liu Cheung Theater',
      'description2': 'Your next stop is the Hooper Student Center',
      'lat': 34.1239612,
      'lng': -117.73957,
      'heading': -12,
      'pitch': 5,
      'marker' : 'True',
    },
    {
      'title': 'Hooper Student Center',
      'description1': 'This is the Hooper Student Center',
      'description2': 'Your next stop is the Price Dining Hall',
      'lat': 34.1236862,
      'lng': -117.73933,
      'heading': 200,
      'pitch': 5,
      'marker' : 'True',
    },
    {
      'title': 'Hooper Student Center2',
      'description1': 'This is the Hooper Student Center',
      'description2': 'Your next stop is the Price Dining Hall',
      'lat': 34.1235417,
      'lng': -117.7393717,
      'heading': 30,
      'pitch': 0,
    },
    {
      'title': 'Hooper Student Center3',
      'description1': 'This is the Hooper Student Center',
      'description2': 'Your next stop is the Price Dining Hall',
      'lat': 34.1235778,
      'lng': -117.7395417,
      'heading': 20,
      'pitch': 0,
    },
    {
      'title': 'Hooper Student Center4',
      'description1': 'This is the Hooper Student Center',
      'description2': 'Your next stop is the Price Dining Hall',
      'lat': 34.1236583,
      'lng': -117.7394533,
      'heading': 0,
      'pitch': 0,
    },
    {
      'title': 'Price Dining Hall',
      'description1': 'This is the Price Dining Hall',
      'description2': 'Your next stop is the Copeland Donahue Theater',
      'lat': 34.1242695,
      'lng': -117.7398867,
      'heading': -5,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Copeland Donahue Theater',
      'description1': 'This is the Copeland Donahue Theater',
      'description2': 'Your next stop is the Vivian Webb Chapel',
      'lat': 34.1244805,
      'lng': -117.739955,
      'heading': 180,
      'pitch': 10,
      'marker' : 'True',
    },
    {
      'title': 'Vivian Webb Chapel',
      'description1': 'This is the Vivian Webb Chapel',
      'description2': 'Your next stop is the Aquatics Center',
      'lat': 34.1250167,
      'lng': -117.740155,
      'heading': 5,
      'pitch': 0,
      'marker' : 'True',
    },
    {
      'title': 'Vivian Webb Chapel2',
      'description1': 'This is the Vivian Webb Chapel',
      'description2': 'Your next stop is the Aquatics Center',
      'lat': 34.1251667,
      'lng': -117.7399667,
      'heading': -5,
      'pitch': 0,
    },
    {
      'title': 'Vivian Webb Chapel3',
      'description1': 'This is the Vivian Webb Chapel',
      'description2': 'Your next stop is the Aquatics Center',
      'lat': 34.1250695,
      'lng': -117.7401167,
      'heading': 0,
      'pitch': 5,
    },
    {
      'title': 'Vivian Webb Chapel4',
      'description1': 'This is the Vivian Webb Chapel',
      'description2': 'Your next stop is the Aquatics Center',
      'lat': 34.1250805,
      'lng': -117.7403383,
      'heading': 0,
      'pitch': 5,
    },
    {
      'title': 'The Crossroad',
      'description1': 'This is the crossroad',
      'description2': 'Your next stop is the Dorm (WSC)',
      'lat': 34.1244722,
      'lng': -117.739145,
      'heading': 170,
      'pitch': 0,
      'marker' : 'True',
    },
    {
      'title': 'Dorm (WSC)',
      'description1': 'This is the Dorm (WSC)',
      'description2': 'Your next stop is the Dorm (VWS)',
      'lat': 34.1252638,
      'lng': -117.7390033,
      'heading': 175,
      'pitch': 0,
      'marker' : 'True',
    },
    {
      'title': 'Dorm (WSC)2',
      'description1': 'This is the Dorm (WSC)',
      'description2': 'Your next stop is the Dorm (VWS)',
      'lat': 34.1256417,
      'lng': -117.7385867,
      'heading': -20,
      'pitch': 0,
    },
    {
      'title': 'Dorm (WSC)3',
      'description1': 'This is the Dorm (WSC)',
      'description2': 'Your next stop is the Dorm (VWS)',
      'lat': 34.1244112,
      'lng': -117.7391033,
      'heading': -20,
      'pitch': 5,
    },
    {
      'title': 'Dorm (VWS)',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1239305,
      'lng': -117.7386633,
      'heading': 190,
      'pitch': 5,
      'marker' : 'True',
    },
    {
      'title': 'Dorm (VWS)2',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1240805,
      'lng': -117.738325,
      'heading': -40,
      'pitch': 0,
    },
    {
      'title': 'Dorm (VWS)3',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1239778,
      'lng': -117.7382717,
      'heading': 175,
      'pitch': 0,
    },
    {
      'title': 'Tennis Fields',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1235138,
      'lng': -117.737695,
      'heading': 0,
      'pitch': 0,
      'marker' : 'True',
    },
    {
      'title': 'Aquatics Center',
      'description1': 'This is the Aquatics Center',
      'description2': 'Your next stop is the Dorm (WSC)',
      'lat': 34.1250945,
      'lng': -117.7385,
      'heading': 135,
      'pitch': 0,
      'marker' : 'True',
    },
    {
      'title': 'Chandler Field',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.125225,
      'lng': -117.737425,
      'heading': 0,
      'pitch': 00,
      'marker' : 'True',
    },
    {
      'title': 'Faculty Field',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1279222,
      'lng': -117.7407117,
      'heading': 180,
      'pitch': 00,
      'marker' : 'True',
    },
    {
      'title': 'Gymnasium',
      'description1': 'This is the Aquatics Center',
      'description2': 'Your next stop is the Dorm (WSC)',
      'lat': 34.1278278,
      'lng': -117.7400533,
      'heading': -30,
      'pitch': 5,
      'marker' : 'True',
    },
    {
      'title': 'Weight Room',
      'description1': 'This is the Aquatics Center',
      'description2': 'Your next stop is the Dorm (WSC)',
      'lat': 34.1280112,
      'lng': -117.7401533,
      'heading': 215,
      'pitch': 5,
    },
    {
      'title': 'Observatory',
      'description1': 'This is the Dorm (VWS)',
      'description2': 'Congradulations! You have finished the virtual tour of the Webb Schools! Click "Next" to exit.',
      'lat': 34.1267528,
      'lng': -117.7408717,
      'heading': 160,
      'pitch': 5,
      'marker' : 'True',
    }
  ];
